name: JDCloud-ER1-Fanchmwrt-Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Initialize environment
        run: |
          sudo apt update -y
          sudo apt full-upgrade -y
          sudo apt install -y binutils bzip2 flex gawk gcc-6+ getopt grep libc-dev libz-dev make4.1+ perl python3.7+ rsync subversion unzip dos2unix libfuse-dev
          sudo bash -c 'bash <(curl -sL https://build-scripts.immortalwrt.org/init_build_environment.sh)'
          sudo apt autoremove -y && sudo apt clean -y

      - name: Update feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Import config
        run: |
          cp deconfig/fanchmwrt_jdcloud_er1.config .config
          make defconfig

      - name: Download dependencies
        run: |
          make download -j$(nproc)
          find dl -size -1024c -exec rm -f {} \;

      - name: Build firmware
        run: |
          make -j$(nproc) || make -j1 V=s

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: jdcloud-er1-firmware
          path: bin/targets/qualcommax/ipq60xx/*.bin
          retention-days: 90
